### PR TITLE
fix: restore force delete of kms keys and key rings

### PR DESCRIPTION
**Pull request by shemau**
### Description

The complete test should force delete the KMS key and key ring.

### Release required?

- [x] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by shemau** [comment]
/run. pipeline

**Comment by shemau** [comment]
```hcl
TestRunAdvancedExampleUpgrade 2024-06-04T14:17:44Z command.go:185: 
TestRunAdvancedExampleUpgrade 2024-06-04T14:17:44Z command.go:185: Terraform used the selected providers to generate the following execution
TestRunAdvancedExampleUpgrade 2024-06-04T14:17:44Z command.go:185: plan. Resource actions are indicated with the following symbols:
TestRunAdvancedExampleUpgrade 2024-06-04T14:17:44Z command.go:185:   ~ update in-place
TestRunAdvancedExampleUpgrade 2024-06-04T14:17:44Z command.go:185: 
TestRunAdvancedExampleUpgrade 2024-06-04T14:17:44Z command.go:185: Terraform will perform the following actions:
TestRunAdvancedExampleUpgrade 2024-06-04T14:17:44Z command.go:185: 
TestRunAdvancedExampleUpgrade 2024-06-04T14:17:44Z command.go:185:   # module.key_protect_all_inclusive.module.kms_key_rings["icd"].ibm_kms_key_rings.key_ring will be updated in-place
TestRunAdvancedExampleUpgrade 2024-06-04T14:17:44Z command.go:185:   ~ resource "ibm_kms_key_rings" "key_ring" {
TestRunAdvancedExampleUpgrade 2024-06-04T14:17:44Z command.go:185:       ~ force_delete  = false -> true
TestRunAdvancedExampleUpgrade 2024-06-04T14:17:44Z command.go:185:         id            = "icd:keyRing:crn:v1:bluemix:public:kms:eu-de:a/abac0df06b644a9cabc6e44f55b3880e:36f730c1-bba7-417e-a53d-575c889cf9f9::"
TestRunAdvancedExampleUpgrade 2024-06-04T14:17:44Z command.go:185:         # (3 unchanged attributes hidden)
TestRunAdvancedExampleUpgrade 2024-06-04T14:17:44Z command.go:185:     }
TestRunAdvancedExampleUpgrade 2024-06-04T14:17:44Z command.go:185: 
TestRunAdvancedExampleUpgrade 2024-06-04T14:17:44Z command.go:185:   # module.key_protect_all_inclusive.module.kms_keys["icd.redis-advanced-upg-1hsz7d-redis"].ibm_kms_key.key will be updated in-place
TestRunAdvancedExampleUpgrade 2024-06-04T14:17:44Z command.go:185:   ~ resource "ibm_kms_key" "key" {
TestRunAdvancedExampleUpgrade 2024-06-04T14:17:44Z command.go:185:       ~ force_delete            = false -> true
TestRunAdvancedExampleUpgrade 2024-06-04T14:17:44Z command.go:185:         id                      = "crn:v1:bluemix:public:kms:eu-de:a/abac0df06b644a9cabc6e44f55b3880e:36f730c1-bba7-417e-a53d-575c889cf9f9:key:17d179dd-553f-4b64-9279-515d69ed16a5"
TestRunAdvancedExampleUpgrade 2024-06-04T14:17:44Z command.go:185:         # (14 unchanged attributes hidden)
TestRunAdvancedExampleUpgrade 2024-06-04T14:17:44Z command.go:185:     }
TestRunAdvancedExampleUpgrade 2024-06-04T14:17:44Z command.go:185: 
TestRunAdvancedExampleUpgrade 2024-06-04T14:17:44Z command.go:185: Plan: 0 to add, 2 to change, 0 to destroy.
TestRunAdvancedExampleUpgrade 2024-06-04T14:17:44Z command.go:185: ╷
```

The change is confined to the complete example used for upgrade testing, related to the KMS module upgrade. Skipping upgrade test.

**Comment by ocofaigh** [comment]
Already addressed in renovate PR - closing

**Pull request closed without merging**
